apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
        - name: classificacao
          image: pivisoto/classificacao
---
apiVersion: v1
kind: Service
metadata:
  name: classificacao-clusterip-service
spec:
  selector:
    app: classificacao
  ports:
  - name: classificacao
    protocol: TCP
    port: 7000
    targetPort: 7000