apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000
