apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs
          image: pivisoto/logs
---
apiVersion: v1
kind: Service
metadata:
  name: logs-clusterip-service
spec:
  selector:
    app: logs
  ports:
  - name: logs
    protocol: TCP
    port: 8000
    targetPort: 8000